"""Initial migration

Revision ID: 11a5a7f7dabb
Revises: 
Create Date: 2024-01-14 09:57:38.573680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a5a7f7dabb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription_purchased', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('subscription_purchased')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
