"""Initial migration.

Revision ID: 75de16efcdd8
Revises: 
Create Date: 2024-01-14 10:50:35.926790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75de16efcdd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription_purchased', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('subscription_purchased')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
