"""Initial migration.

Revision ID: 9adc60a84819
Revises: 
Create Date: 2023-12-13 14:19:41.441746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adc60a84819'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['file_name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('given_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('family_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('locale', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('locale')
        batch_op.drop_column('picture')
        batch_op.drop_column('family_name')
        batch_op.drop_column('given_name')
        batch_op.drop_column('name')

    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
