"""change type double

Revision ID: 9c3fc41b5ec4
Revises: 7991dd3662d0
Create Date: 2024-01-16 19:39:00.836213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3fc41b5ec4'
down_revision = '7991dd3662d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
