"""empty message

Revision ID: b775f8813dc5
Revises: 93d30318a230
Create Date: 2024-01-07 21:58:22.915709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b775f8813dc5'
down_revision = '93d30318a230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_stripe_customer_id_key', type_='unique')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_stripe_customer_id_key', ['stripe_customer_id'])

    # ### end Alembic commands ###
